image: hub.c.163.com/qingzhou/maven-tomcat:8-jdk8-4
variables:
  # Please edit to your GitLab project
  CI_REGISTRY_IMAGE: ${CI_REGISTRY}/qingzhou/apigw-portal
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  branch_url: $CI_PROJECT_URL/tree/$CI_COMMIT_REF_NAME

stages:
  - commit-check
  - test

before_script:
  - export MAVEN_HOME=/usr/local/bin/apache-maven-3.6.3

commit-check:
  stage: commit-check
  script:
    - chmod +x scripts/check_mr_message.sh
    - scripts/check_mr_message.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - qz-gitlab-runner

job_unit_test:
  stage: test
  script:
    - pwd
    - git status
    - $MAVEN_HOME/bin/mvn clean package -U -Dmaven.test.failure.ignore=true
    - git status
    - echo "now unit_test finished."
  artifacts:
    paths:
      - /builds/qingzhou/nce-gdashboard/nce-gdashboard-backend
  tags:
    - qz-gitlab-runner





